t_prty_jdgmt:
  column_names: 
    - prcs_trgt_trnspt_info_key
    - prd_pln_id 
    - fg_do_num
    - do_fg_ship_num
    - ord_num
    - bu_cd
    - itm_cd
    - prcs_trgt_etd_wks
    - prcs_trgt_exp_fctry_date_acqstn_rang
    - wh_alctn_dy
    - init_alctn_date
    - nw_itm_trgt_srch_flg
    - cont_itm_alctn_date
    - max_trnspt_lt
    - fstst_trnspt_mthd_cd
    - fstst_eta_wh
    - pjt_itm_ctgry_cd
    - core_itm_ctgry_cd
    - opnty_loss_amt
    - gp_ttl_amt
    - crnt_prc_ttl_amt
    - trnspt_mthd_alctn_trgt_flg
    - trnspt_mthd_asgned_flg
    - prty
    - rgst_dtime
  column_types:
    - int64
    - int64
    - str
    - int64
    - str
    - str
    - str
    - int64
    - int64
    - date
    - date
    - str
    - date
    - int64
    - str
    - date
    - str
    - str
    - int64
    - int64
    - int64
    - str
    - str
    - int64
    - date
  max_lengths:
    - 99999
    - 99999
    - 100
    - 99999
    - 100
    - 100
    - 100
    - 99999
    - 99999
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 1
    - '%Y-%m-%d'
    - 99999
    - 100
    - '%Y-%m-%d'
    - 100
    - 100
    - 99999
    - 99999
    - 99999
    - 1
    - 1
    - 99999
    - '%Y-%m-%d %H:%M:%S+00:00'
t_airt_trgt:
  column_names: 
    - alrt_key
    - prcs_trgt_trnspt_info_key 
    - trnspt_mthd_fnl_trnspt_info_key
    - prd_pln_id
    - fg_do_num
    - do_fg_ship_num
    - bu_cd
    - alrt_trgt_func_cd
    - alrt_type
    - alrt_msg
    - sls_sum_cd
    - itm_cd
    - set_cd
    - sku_id
    - sku_cd
    - out_inv_num
    - out_inv_repl_qty
    - splt_rcmnd_pcs_qty
    - splt_rcmnd_bxs_qty
    - rcmnd_trnspt_mthd_cd
    - rcmnd_etd
    - rcmnd_dptr_port_cd
    - rcmnd_trnspt_to_port_cd
    - rcmnd_crrr_name
    - rcmnd_srvc_cd
    - rcmnd_flight_num
    - wh_cd
    - gnrl_cd_1
    - gnrl_cd_2
    - gnrl_cd_3
    - gnrl_cd_4
    - gnrl_cd_5
    - rgst_dtime
  column_types:
    - int64
    - int64
    - int64
    - int64
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - int64
    - int64
    - int64
    - int64
    - str
    - date
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - date
  max_lengths:
    - 99999
    - 99999
    - 99999
    - 99999
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 99999
    - 99999
    - 99999
    - 99999
    - 100
    - '%Y-%m-%d'
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - '%Y-%m-%d %H:%M:%S+00:00'
t_out_inv_sku_calc_rslt:
  column_names: 
    - prcs_trgt_trnspt_info_key
    - fg_do_num
    - do_fg_ship_num
    - ord_num
    - bu_cd
    - sls_sum_cd
    - itm_id
    - itm_cd
    - set_cd
    - set_type_cd
    - sku_id
    - sku_cd
    - cl_id
    - cl_cd
    - sz_id
    - sz_cd
    - lgth_id
    - lgth_cd
    - pckg_qty
    - out_inv_num
    - out_inv_repl_num
    - splt_rcmnd_pcs_qty
    - splt_rcmnd_bxs_qty
    - rgst_dtime
  column_types:
    - int64
    - str
    - str
    - str
    - str
    - str
    - int64
    - str
    - str
    - str
    - int64
    - str
    - int64
    - str
    - int64
    - str
    - int64
    - str
    - int64
    - int64
    - int64
    - int64
    - int64
    - date
  max_lengths:
    - 99999
    - 100
    - 100
    - 100
    - 100
    - 100
    - 99999
    - 100
    - 100
    - 100
    - 99999
    - 100
    - 99999
    - 100
    - 99999
    - 100
    - 99999
    - 100
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - '%Y-%m-%d %H:%M:%S+00:00'
t_sls_inv_stk_pln_by_rgn_by_sku:
  column_names: 
    - ord_main_rgn_cd
    - bu_cd
    - wk_start_date
    - itm_id
    - itm_cd
    - sku_id
    - sku_cd
    - sls_pln_qty
    - str_inv_qty
    - str_std_inv_qty
    - str_tsf_in_pln_qty_qty
    - sched_tsf_out_qty
    - wh_inv_qty
    - wh_tsf_in_pln_qty_qty
    - wh_inv_pln_qty
    - wh_roq
    - cl_id
    - cl_cd
    - sz_id
    - sz_cd
    - lgth_id
    - lgth_cd
    - rgst_dtime
  column_types:
    - str
    - str
    - date
    - int64
    - str
    - int64
    - str
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - str
    - int64
    - str
    - int64
    - str
    - date
  max_lengths:
    - 100
    - 100
    - '%Y-%m-%d'
    - 99999
    - 100
    - 99999
    - 100
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 100
    - 99999
    - 100
    - 99999
    - 100
    - '%Y-%m-%d %H:%M:%S+00:00'
t_trnspt_mthd_fnl_trnspt_info:
  column_names: 
    - trnspt_mthd_fnl_trnspt_info_key
    - prd_pln_id
    - fg_do_num
    - do_fg_ship_num
    - ord_num
    - bu_cd
    - do_sts_cd
    - exe_pln_sts_cd
    - dely_core_rspnsblty
    - trnspt_cond_cd
    - brnch_fctry_cd
    - itm_cd
    - wh_cd
    - exp_fctry_date
    - bk_capa_cbm
    - ttl_wght
    - chgbl_wght
    - trnspt_mthd_cd
    - etd_date
    - dptr_port_cd
    - trnspt_to_port_cd
    - crrr_name
    - flight_num
    - rcmnd_cntnr_grp_num
    - rcmnd_cy_cfs_type
    - mlt_trnspt_prcs_grp_no
    - rgst_dtime
  column_types:
    - int64
    - int64
    - str
    - int64
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - date
    - int64
    - int64
    - int64
    - str
    - date
    - str
    - str
    - str
    - str
    - int64
    - str
    - int64
    - date
  max_lengths:
    - 99999
    - 99999
    - 100
    - 99999
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - '%Y-%m-%d'
    - 99999
    - 99999
    - 99999
    - 100
    - '%Y-%m-%d'
    - 100
    - 100
    - 100
    - 100
    - 99999
    - 100
    - 99999
    - '%Y-%m-%d %H:%M:%S+00:00'
t_prcs_trgt_trnspt_info:
  column_names: 
    - prcs_trgt_trnspt_info_key
    - sls_sum_cd
    - prd_pln_id
    - fg_do_num
    - do_fg_ship_num
    - ord_num
    - bu_cd
    - do_sts_cd
    - exe_pln_sts_cd
    - dely_core_rspnsblty
    - trn_ptn_cd
    - trnspt_mthd_cd
    - air_chrtr_flg
    - trnspt_cond_cd
    - mfctry_cd
    - brnch_fctry_cd
    - itm_cd
    - wh_cd
    - exp_fctry_date
    - ship_qty_plu
    - org_cntry_cd
    - bk_capa_cbm
    - ttl_wght
    - chgbl_wght
    - cntrct_etd
    - po_wh
    - eta_wh
    - cst_amt
    - org_prc
    - crnt_prc
    - dptr_port_cd
    - trnspt_to_port_cd
    - sls_cntry_cd
    - rcmnd_trnspt_mthd_cd
    - rcmnd_etd
    - rcmnd_dptr_port_cd
    - rcmnd_trnspt_to_port_cd
    - rcmnd_crrr_name
    - rcmnd_srvc_cd
    - rcmnd_cntnr_grp_num
    - rcmnd_flight_num
    - rcmnd_cy_cfs_type
    - rcmnd_trnspt_mthd_wh_arrvl_date
    - rcmnd_exp_fctry_date
    - rcmnd_air_few
    - rcmnd_air_rate_type
    - prev_rcmnd_trnspt_mthd_cd
    - prev_rcmnd_etd
    - prev_rcmnd_dptr_port_cd
    - prev_rcmnd_trnspt_to_port_cd
    - prev_rcmnd_crrr_name
    - prev_rcmnd_flight_num
    - prev_rcmnd_cy_cfs_type
    - prev_rcmnd_trnspt_mthd_wh_arrvl_date
    - prev_rcmnd_exp_fctry_date
    - prev_rcmnd_air_few
    - prev_rcmnd_air_rate_type
    - prcs_trgt_etd_wks
    - prcs_trgt_exp_fctry_date_acqstn_rang
    - wh_alctn_date
    - init_alctn_date
    - nw_itm_trgt_srch_flg
    - cont_itm_alctn_date
    - max_trnspt_lt
    - fstst_trnspt_mthd_cd
    - fstst_eta_wh
    - pjt_itm_ctgry_cd
    - core_itm_ctgry_cd
    - opnty_loss_amt
    - gp_ttl_amt
    - crnt_prc_ttl_amt
    - trnspt_mthd_alctn_trgt_flg
    - trnspt_mthd_asgned_flg
    - prty
    - air_chrtr_alctn_trgt_flg
    - max_trnspt_lt_thrs
    - air_chrtr_exp_fctry_date_rang_from
    - air_chrtr_exp_fctry_date_rang_to
    - air_chrtr_per_subdo_prd_pln_trnspt_cst
    - air_chrtr_per_pcs_expc_cst_rtio
    - air_chrtr_expc_wh_arrvl_date
    - cst_rtio
    - per_subdo_prd_pln_trnspt_cst
    - per_pcs_trnsprttn_cst
    - per_pcs_expc_cst_incld_trnsprttn_cst
    - alctn_trgt_flg
    - mlt_trnspt_alctn_trgt_flg
    - ship_lt_btw_brnch_fctry_and_wh
    - mlt_trnspt_prcs_grp_no
    - mlt_trnspt_basis_rec_flg
    - mlt_trnspt_tnttv_rcmnd_trnspt_mthd
    - mlt_trnspt_tnttv_rcmnd_trnspt_mthd_dptr_port_cd
    - mlt_trnspt_tnttv_rcmnd_trnspt_mthd_trnspt_to_port_cd
    - mlt_trnspt_tnttv_rcmnd_trnspt_mthd_mlt_srvc
    - exprs_ship_expc_exp_fctry_date
    - exprs_ship_expc_cut_date
    - exprs_ship_expc_etd
    - exprs_ship_expc_dptr_port_cd
    - exprs_ship_expc_trnspt_to_port_cd
    - exprs_ship_expc_srvc
    - exprs_ship_expc_best_cbm
    - exprs_ship_expc_max_cbm
    - exprs_ship_per_cntnr_trnspt_cst
    - exprs_ship_espc_cntnr_qty
    - exprs_ship_expc_cntnr_trnspt_cst
    - exprs_ship_expc_cntnr_usg_cbm
    - exprs_ship_per_subdo_prd_pln_trnspt_cst
    - exprs_ship_per_pcs_expc_trnspt_cst
    - exprs_ship_per_pcs_expc_cst_incld_trnspt_cst
    - exprs_ship_per_pcs_expc_cst_rtio
    - exprs_ship_expc_cy_cfs_type
    - exprs_ship_expc_wh_arrvl_date
    - air_expc_exp_fctry_date
    - air_expc_etd
    - air_expc_dptr_port_cd
    - air_expc_trnspt_to_port_cd
    - air_expc_few
    - air_expc_rate_type
    - air_expc_bff_rate
    - air_expc_min_cnsmptn_chgbl_wght
    - air_expc_bk_lw_lmt_cbm
    - air_expc_start_yr_mo
    - air_expc_end_yr_mo
    - air_expc_wh_arrvl_date
    - air_expc_wk_start_date
    - air_expc_wk_end_date
    - air_expc_wkly_capa_cbm
    - air_expc_wkly_capa_chgbl_wght
    - air_per_subdo_prd_pln_trnspt_cst
    - air_per_pcs_expc_trnspt_cst
    - air_per_pcs_expc_cst_incld_trnspt_cst
    - air_per_pcs_expc_cst_rtio
    - air_expc_cy_cfs_type
    - air_nxt_wk_expc_exp_fctry_date
    - air_nxt_wk_expc_etd
    - air_nxt_wk_expc_dptr_port_cd
    - air_nxt_wk_expc_trnspt_to_port_cd
    - air_nxt_wk_expc_few
    - air_nxt_wk_expc_rate_type
    - air_nxt_wk_expc_bff_rate
    - air_nxt_wk_expc_min_cnsmptn_chgbl_wght
    - air_nxt_wk_expc_bk_lw_lmt_cbm
    - air_nxt_wk_expc_start_yr_mo
    - air_nxt_wk_expc_end_yr_mo
    - air_nxt_wk_expc_wh_arrvl_date
    - air_nxt_wk_expc_wk_start_date
    - air_nxt_wk_expc_wk_end_date
    - air_nxt_wk_expc_wkly_capa_cbm
    - air_nxt_wk_expc_wkly_capa_chgbl_wght
    - air_per_subdo_prd_pln_nxt_wk_trnspt_cst
    - air_per_pc_nxt_wk_expc_trnspt_csts
    - air_per_pcs_nxt_wk_expc_cst_incld_trnspt_cst
    - air_per_pcs_nxt_wk_expc_cst_rtio
    - air_nxt_wk_expc_cy_cfs_type
    - ship_type
    - strct_cmmtte
    - capa_exceedbl_flg
    - bs_port_flg
    - bs_date_wk
    - bs_port_lt
    - etd_wk
    - trnspt_lt
    - load_prcntg
    - cmmtte_yr_mo
    - moly_cntnr_capa
    - moly_asgned_cntnr_qty
    - wk_start_date
    - wk_end_date
    - bs_date
    - etd_date
    - ship_exp_fctry_date_rang_from
    - ship_exp_fctry_date_rang_to
    - ship_eta
    - ship_alctn_date_rang_from
    - ship_alctn_date_rang_to
    - wkly_cntnr_capa
    - dstr_aft_wkly_cntnr_capa
    - wk_cntn_unusd_shppng_cmpny_cbm
    - wk_asgnmnt_cbm
    - lrg_cntnr_sz_cd
    - sml_cntnr_sz_cd
    - std_cntnr_qty
    - std_cntnr_min_cbm
    - std_cntnr_b_cbm
    - std_cntnr_max_cbm
    - asgned_cbm
    - cnsmptn_lrg_cntnr_qty
    - cnsmptn_sml_cntnr_qty
    - cnsmptn_cntnr_qty_by_teu
    - init_asrt_flg
    - ship_expc_wh_arrvl_date
    - rgst_dtime
  column_types:
    - int64
    - str
    - int64
    - str
    - int64
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - str
    - date
    - int64
    - str
    - int64
    - int64
    - int64
    - date
    - date
    - date
    - int64
    - int64
    - int64
    - str
    - str
    - str
    - str
    - date
    - str
    - str
    - str
    - str
    - int64
    - str
    - str
    - date
    - date
    - str
    - str
    - str
    - date
    - str
    - str
    - str
    - str
    - str
    - date
    - date
    - str
    - str
    - int64
    - int64
    - date
    - date
    - str
    - date
    - int64
    - str
    - date
    - str
    - str
    - int64
    - int64
    - int64
    - str
    - str
    - int64
    - str
    - int64
    - int64
    - int64
    - int64
    - int64
    - date
    - int64
    - int64
    - int64
    - int64
    - str
    - str
    - int64
    - int64
    - str
    - str
    - str
    - str
    - str
    - date
    - date
    - date
    - str
    - str
    - str
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - str
    - date
    - date
    - date
    - str
    - str
    - str
    - str
    - int64
    - int64
    - int64
    - date
    - date
    - date
    - date
    - date
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - str
    - date
    - date
    - str
    - str
    - str
    - str
    - int64
    - int64
    - int64
    - date
    - date
    - date
    - date
    - date
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - str
    - str
    - str
    - str
    - str
    - int64
    - int64
    - int64
    - int64
    - int64
    - date
    - int64
    - int64
    - date
    - date
    - date
    - date
    - int64
    - int64
    - date
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - str
    - str
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - int64
    - str
    - date
    - date
  max_lengths:
    - 99999
    - 100
    - 99999
    - 100
    - 99999
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 100
    - 1
    - 100
    - 100
    - 100
    - 100
    - 100
    - '%Y-%m-%d'
    - 99999
    - 100
    - 99999
    - 99999
    - 99999
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 99999
    - 99999
    - 99999
    - 100
    - 100
    - 100
    - 100
    - '%Y-%m-%d'
    - 100
    - 100
    - 100
    - 100
    - 99999
    - 100
    - 100
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 100
    - 100
    - 100
    - '%Y-%m-%d'
    - 100
    - 100
    - 100
    - 100
    - 100
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 100
    - 100
    - 99999
    - 99999
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 1
    - '%Y-%m-%d'
    - 99999
    - 100
    - '%Y-%m-%d'
    - 100
    - 100
    - 99999
    - 99999
    - 99999
    - 1
    - 1
    - 99999
    - 1
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - '%Y-%m-%d'
    - 99999
    - 99999
    - 99999
    - 99999
    - 1
    - 1
    - 99999
    - 99999
    - 1
    - 100
    - 100
    - 100
    - 100
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 100
    - 100
    - 100
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 100
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 100
    - 100
    - 100
    - 100
    - 99999
    - 99999
    - 99999
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 100
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 100
    - 100
    - 100
    - 100
    - 99999
    - 99999
    - 99999
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 100
    - 100
    - 100
    - 1
    - 1
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - '%Y-%m-%d'
    - 99999
    - 99999
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - '%Y-%m-%d'
    - 99999
    - 99999
    - '%Y-%m-%d'
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 100
    - 100
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 99999
    - 100
    - '%Y-%m-%d'
    - '%Y-%m-%d %H:%M:%S+00:00' 